### ISSUE TITLE
PrintFilesGax not defined error

### ISSUE THREAD

**Issue by renormalization2** [canorve/EllipSect#3]
Hi. I found this bug while using the code.
Whenever I include  '--sbout' in the command, this error arises both in the terminal and Python IDE.
Ex) ellipsect galfit.08 --sbout
I really need the surface brightness information instead of fixed plots, so would you care to review this issue?
![image](https://github.com/canorve/EllipSect/assets/103830138/588654ad-c73b-4158-935f-3eb421bc317a)

**Comment by canorve** [comment]
Hello, thank you for bringing this to my attention.

I had previously identified this issue and have since resolved it. You may now download the code with the latest version. Alternatively, if you can wait for a few days, I will be adding a few new features to the code and will update pip. I hope to release the updated version by the end of this week.

**Comment by canorve** [comment]
The bug has been fixed in the latest release of Ellipsect: v3.2.2.

Now you can update to the new version via pip.

**Comment by renormalization2** [comment]
Thank you very much for handling it this quickly.

Besides, I'd love to know how the error bars of radial SB profiles are estimated. Does it use the sigma weight image specified in 'galfit.xx'?
It would be great if I can find a paper explaining the process.

**Comment by canorve** [comment]
No, I am not utilizing the Sigma weight image. Instead, the error bars in the radial profile are calculated by taking the sectors' average at that particular radius. The galaxy is divided into equally spaced ellipse sectors based on its angular position and axis ratio, as it is given in galfit.XX.

I apologize, but the paper is currently under development. However, we plan to submit it to a journal soon. I'm using 
the sector_photometry routine of MGE from Cappellari (2002) if that is useful to you.

I hope that answers your question. If you have any further questions or concerns, 
please do not hesitate to contact me. I'm open to suggestions to improve the code.
